---
apiVersion: v1
kind: Service
metadata:
  name: helm-jenkins
  namespace: helm-jenkins
spec:
  ports:
    - name: master
      port: {{ index .Values "containerPort" "http-port" }}
      targetPort: {{ index .Values "containerPort" "http-port" }}
    - name: slave
      port: {{ index .Values "containerPort" "jnlp-port" }}
      targetPort: {{ index .Values "containerPort" "jnlp-port" }}
  selector:
    app: helm-jenkins
